### ISSUE TITLE
When I linkify the text like "{url: https:abc.com}" or "{url: https:abc.com, msg:abc}", the "," and "}" are identified into linkified text.

### ISSUE THREAD

**Issue by Onekki** [Cretezy/flutter_linkify#105]
When I linkify the text like "{url: https:abc.com}" or "{url: https:abc.com, msg:abc}", the "," and "}" are identified into linkified text.

**Comment by sebastianbuechler** [comment]
`https:abc.com` is not a valid url. If I changed it to `{url: https://abc.com, msg:abc}` it correctly identifies `https:abc.com` as link. What did you expect?
![image](https://user-images.githubusercontent.com/42775578/172842140-4d3145a6-0db2-44bd-8838-4f3c66656d37.png)
