### ISSUE TITLE
Support for URL without HTTP

### ISSUE THREAD

**Issue by scottdewald** [Cretezy/flutter_linkify#13]
Thanks for this great library. I am currently using it in one of my applications and it works great.

It appears that links only work if they are prefixed with `http://` or `https://`. Could you also support links like `www.google.com`? My application has a lot of user-generated content and I have noticed some users do not add `https://` when typing out links.

**Comment by Cretezy** [comment]
Check out Cretezy/linkify, we have a ticket there for loose URLs (what you are asking)!

**Comment by pmrajani** [comment]
@scottdewald Can i show code please!

**Comment by kleyos** [comment]
> Check out Cretezy/linkify, we have a ticket there for loose URLs (what you are asking)!

not at all. every string with dot is not a link
