### ISSUE TITLE
Expose maxLines and overflow RichText Fields

### ISSUE THREAD

**Issue by scottdewald** [Cretezy/flutter_linkify#17]
Just like you expose the `textAlign` and `textDirection` `RichText` fields within the `Linkify` class, can you also please expose the `maxLines` and `overflow` fields? Something like:

```
    class Linkify extends StatelessWidget {
         ...

        final int maxLines;
        final TextOverflow overflow;

        const Linkify({
            ...
            this.maxLines,
            this.overflow = TextOverflow.ellipsis,
        }) : super(key: key);

        @override
        Widget build(BuildContext context) {
            final elements = linkify(
                text,
                humanize: humanize,
                linkTypes: linkTypes,
            );

            return RichText(
                textAlign: textAlign,
                textDirection: textDirection,
                maxLines: maxLines,
                overflow: overflow,
                ...
            );
        }
     }

```

Thanks again for this great utility package.

**Comment by scottdewald** [comment]
By the way, I made the change locally and verified links still work properly if you set `maxLines` and the link is partially truncated.

**Comment by Cretezy** [comment]
Ah damn I'm so sorry, this slipped under my radar (damn GitHub notifications!). I've merged your PR and will close this, I will push the update soon

**Comment by Shubham-VE** [comment]
Can we do this for SelectableLinkify too?
