### ISSUE TITLE
Why is this widget not extending the "Text" widget?

### ISSUE THREAD

**Issue by ali-thowfeek** [Cretezy/flutter_linkify#20]
Because, if it would then we would have all the features it provides, like the `maxLines`, `text overflow` and many more...

**Comment by Cretezy** [comment]
You can provide many of these features to the RichText widget too, which is required to have multi-section of texts. Which features do you need?

**Comment by ali-thowfeek** [comment]
I needed `maxLines`,text `overflow` to make an expandable text widget which recognizes links at the same time. `flutter_linkify` was promising, but got stuck on the way. I also wanted to render html & css on that widget, so I guess i'll have to figure out another way somehow.
