### ISSUE TITLE
Text size problem

### ISSUE THREAD

**Issue by mudi256** [Cretezy/flutter_linkify#22]
text size not change according to mobile font size.
When we change the mobile font size (small to large or large to small) from settings linkify text font size not change, while in whole app all Text font size change according to mobile font size.

**Comment by Cretezy** [comment]
Can you please add a code example?

**Comment by mudi256** [comment]
> Can you please add a code example?

below is code snippet
`Linkify(
                                onOpen: (link) async {
                                  if (await canLaunch(link.url)) {
                                    await launch(link.url);
                                  } else {
                                    throw 'Could not launch $link';
                                  }
                                },
                                text :document['content'],
                                style: TextStyle(color: Colors.white),
                                linkStyle: TextStyle(color: Colors.black),
                              ),`

**Comment by Cretezy** [comment]
Sorry this wouldn't be related to this library I think. It uses RichText and TextSpans to build the widgets, so this would be upstream with Flutter.

You can pass in a size to the TextStyle which would work though. If you can give me a better example I can probably help

**Comment by Nanthno** [comment]
In case anyone else encounters this issue, the workaround I found is to manually set textScaleFactor in the Linkify constructor to MediaQuery.of(context).textScaleFactor
