### ISSUE TITLE
Linkify Multiple URLs in one String

### ISSUE THREAD

**Issue by altShiftDev** [Cretezy/flutter_linkify#24]
Hi, It would be nice if the plugin could handle a case like the following:

> "email me at mailto:test@test.com or visit my website https://test.com, or this other website abc.test.com"

Currently it ignores the email if it finds a link and can only find a link if http/https is prefixed. Once it finds any match it will ignore the rest of the string, even if other valid matches exist.

**Comment by pilotviper134** [comment]
Any ideas how to fix this?

**Comment by Cretezy** [comment]
This is supported, the email should not have `mailto:` at the start to be reconized. You can implement a custom parser for `mailto:` if you'd like using the latest version and a parser for https://github.com/Cretezy/linkify
