### ISSUE TITLE
Please release the next version

### ISSUE THREAD

**Issue by charleshan** [Cretezy/flutter_linkify#25]
It looks like this repo merged a pull request that added `maxlines` and `overflow` a few months back. It would be great to have these available as a release.

Thanks!

**Comment by pilotviper134** [comment]
I agree! We need new update

**Comment by Cretezy** [comment]
Will do tonight

**Comment by charleshan** [comment]
/reminder

😁

**Comment by Cretezy** [comment]
Done! Sorry for being late
