### ISSUE TITLE
Great util in Flutter, how about multi url in one text though?

### ISSUE THREAD

**Issue by jinfagang** [Cretezy/flutter_linkify#3]
Hi, this is helpful, would u like to add multi url support? It's a little complicated casue we have to solve every url click event

**Comment by Cretezy** [comment]
Sorry, I don't understand what you mean. Could you explain in better details and provide an example?

**Comment by jinfagang** [comment]
@Cretezy Thanks your response!! I mean something like this:

text:

```
this is a long text and it contains 2 or more urls, such as baidu.com or bing.com, how to detection both of them?
```

Simply, how to recognize those 2 urls (or more), and corresponding each one open event action.

BTW, how to enable the `baidu.com` and `www.baidu.com` linkify rather than only `http://baidu.com`?

**Comment by Cretezy** [comment]
The multi URLs already should work.

The mode without http is "loose", and is not implemented yet

**Comment by jinfagang** [comment]
@Cretezy Seems long time ago communit got this problem but still not done yet, is that very complicated? I am totally new to dart but I would definitely wanna help if you have some solution to get it done... We really need such a maintained and useful lib

**Comment by Cretezy** [comment]
Hey! v1.0.4 should have a fix for this. (https://github.com/Cretezy/flutter_linkify/issues/1)
