### ISSUE TITLE
Support SelectableText

### ISSUE THREAD

**Issue by MTRNord** [Cretezy/flutter_linkify#30]
In Flutter 1.9 there is a way to make text selectable. It would be awesome if this can be activated for this lib to allow text to get copied. :D 

https://api.flutter.dev/flutter/material/SelectableText-class.html

**Comment by Cretezy** [comment]
Sounds fairly easy to support, will add over the weekend!

**Comment by MTRNord** [comment]
Awesome thanks!

**Comment by Cretezy** [comment]
Done! Sorry if it took a bit longer than expected. With v3.1.0 you can use SelectableLinkify!

**Comment by MTRNord** [comment]
Thanks a lot!

**Comment by sherazahmad720** [comment]
There is no option to change the selection colours  and handles colours when selecting a text.
if you add this it will become awesome
