### ISSUE TITLE
Compiler error with Theme

### ISSUE THREAD

**Issue by iamatulkumar** [Cretezy/flutter_linkify#37]
Compiler message:
../../../../Documents/flutter_tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_linkify-3.1.3/lib/flutter_linkify.dart:113:44: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../../Documents/flutter_tools/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
        style: Theme.of(context).textTheme.bodyText2.merge(style),
                                           ^^^^^^^^^
../../../../Documents/flutter_tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_linkify-3.1.3/lib/flutter_linkify.dart:117:14: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../../Documents/flutter_tools/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
            .bodyText2
             ^^^^^^^^^
../../../../Documents/flutter_tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_linkify-3.1.3/lib/flutter_linkify.dart:243:44: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../../Documents/flutter_tools/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
        style: Theme.of(context).textTheme.bodyText2.merge(style),
                                           ^^^^^^^^^
../../../../Documents/flutter_tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_linkify-3.1.3/lib/flutter_linkify.dart:247:14: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../../Documents/flutter_tools/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
            .bodyText2

**Comment by Cretezy** [comment]
`flutter upgrade`

You are likely running a very old version of Flutter.
