### ISSUE TITLE
 Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by shivamgupta** [Cretezy/flutter_linkify#40]
Gives the following error after adding flutter_linkify: ^3.1.3 to pubspec.yaml 

Compiler message:
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_linkify-3.1.3/lib/flutter_linkify.dart:113:44: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../Developer/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
        style: Theme.of(context).textTheme.bodyText2.merge(style),
                                           ^^^^^^^^^

**Comment by Cretezy** [comment]
`flutter upgrade`, please use a recent flutter version
