### ISSUE TITLE
pubspec.yaml does not specify a minimum Flutter version

### ISSUE THREAD

**Issue by jamesderlin** [Cretezy/flutter_linkify#44]
To avoid issues like https://github.com/Cretezy/flutter_linkify/issues/40 or https://stackoverflow.com/questions/62196357/, flutter_linkify's `pubspec.yaml` file should specify the minimum required Flutter version.  The new `TextTheme` properties require Flutter 1.13.8 or newer.

**Comment by Cretezy** [comment]
This is a good idea. Will add soon

**Comment by Cretezy** [comment]
This has been added in https://github.com/Cretezy/flutter_linkify/commit/bc6608f760a2bf1544d670bf38f08ff83cdbd958

Thank you!
