### ISSUE TITLE
Thank you for making the module easy to use

### ISSUE THREAD

**Issue by keehyun2** [Cretezy/flutter_linkify#45]
Thank you for making the module easy to use

Can I ask for one additional feature development?

I wish I had the ability to find the **phone number** in the sentence.

Is that possible?

I would like to ask if possible.

**Comment by Cretezy** [comment]
Phone numbers are much much harder to parse, because there's dozens of formats with different lenghts.

https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers
