### ISSUE TITLE
Url not opening in slectable linkify

### ISSUE THREAD

**Issue by Xatta-Trone** [Cretezy/flutter_linkify#55]
hello...thank you for making this awesome package. 
I am using this for one of my projects. However, Linkify widget is working as expected, but when I changed it to SelectableLinkify then the link is not working anymore. but the text can be selected. 
**how to implement both behaviour ?**

**Comment by jamesilloyd** [comment]
I am also having this problem as well.

**Comment by cmaster11** [comment]
I think this was related to https://github.com/Cretezy/flutter_linkify/issues/31 , and it is now officialy in stable as of Flutter 1.20.0 release. Verified myself this is now working! 

Can you please try to use the latest stable? 😄

**Comment by Cretezy** [comment]
Yes, this should now be fixed in the latest versions of Flutter!
