### ISSUE TITLE
Unable select text when SelectableLinkify has link on it

### ISSUE THREAD

**Issue by rifaldhiaw** [Cretezy/flutter_linkify#59]
Hi, thanks for the handy package.   

I face an issue here, when I use `SelectableLinkify` and it has a link on the text, I become unable to select the text.
if I use `showCursor: true,`, it is showing the cursor does not move from its first position
I am currently developing in the flutter web, in case if it is only happening in this platform.

Thanks

**Comment by Cretezy** [comment]
Could you please provide a code example I can run to debug this? Thank you!

**Comment by dannnnthemannnn** [comment]
Same problem for me.

`
                      SelectableLinkify(
                        text: 'This is a sample message containing a link www.google.com. Hopefully it helps debug!',
                        style: TextStyle(fontSize: 15),
                        onOpen: (link) async {
                          print(link);
                        },
                      )
`

**Comment by dannnnthemannnn** [comment]
Maybe related? https://github.com/flutter/flutter/issues/61992

**Comment by Cretezy** [comment]
The error posted by @dannnnthemannnn is likely the problem. I will mark as an upstream issue

**Comment by Cretezy** [comment]
Bug was fixed upstream. Please retest and reopen if not fixed!
