### ISSUE TITLE
Text Overflowing is not handled 

### ISSUE THREAD

**Issue by varsvat** [Cretezy/flutter_linkify#60]
We can not use any type of overflow techniques(like ellipsis , fade , etc..) which are available with the normal text widget

**Comment by Cretezy** [comment]
Closing as we now have the `overflow` option (been a while). Feel free to reopen if doesn't solve your issue

**Comment by Shubham-VE** [comment]
SelectableLinkify widget does not have an overflow field like Linkify widget has.
