### ISSUE TITLE
Linkify dont work when wrapped in CupertinoButton.filled Button

### ISSUE THREAD

**Issue by janbildsoehansen** [Cretezy/flutter_linkify#63]
Hey im new to flutter and im facing a issuse with Linkify dont work when wrapped in CupertinoButton.filled Button
im i doing it wrong or..??

                              CupertinoButton.filled(
                                  child: Text(landmark.hjemmeside),
                                  onPressed: () {
                                    Linkify(
                                      onOpen: (link) async {
                                        if (await canLaunch(link.url)) {
                                          await launch(link.url);
                                        } else {
                                          throw 'Could not launch $link';
                                        }
                                        },
                                      text: landmark.hjemmeside,
                                    );
                                  },
                                ),

**Comment by aaqibism** [comment]
You don't need to use a button unless you want the entire text to be clickable. If you only want the hyperlink to be clickable but have the style of a button consider wrapping your Linkify in a Container and styling it like a button.

**Comment by janbildsoehansen** [comment]
Thanks for your answer will try that

**Comment by Cretezy** [comment]
@janbildsoehansen Closing as it you seem to have found the solution. Feel free to reopen!
