### ISSUE TITLE
Cursor Stuck

### ISSUE THREAD

**Issue by dvird** [Cretezy/flutter_linkify#67]
When im setting ontap there is problem what the cursor is showing up and stuck. no matter what i do its not gone

![WhatsApp Image 2020-12-20 at 10 05 19](https://user-images.githubusercontent.com/42498461/102709118-04f87080-42b0-11eb-8c6e-85811ba81afe.jpeg)

**Comment by Cretezy** [comment]
Has this been fixed? This was likely a problem with Flutter itself.

Feel free to reopen if it's not solved!
