### ISSUE TITLE
Support for email addresses

### ISSUE THREAD

**Issue by PieterAelse** [Cretezy/flutter_linkify#7]
Could support be added for email addressed? So when a text contains `xxx@xx.xx` (see dart linkify package for regex), it's clickable.

Adding support for subject and body would be even more awesome!
 `url_launcher` should be able to handle `subject` and `body` too.

**Comment by Cretezy** [comment]
This seems like a great use-case, I'll look into adding it to the next version. Feel free to open a PR!

**Comment by PieterAelse** [comment]
If only I had time! 😜

**Comment by Cretezy** [comment]
Thanks a lot @PieterAelse for the great work on this!

**Comment by PieterAelse** [comment]
You're welcome @Cretezy! Cool to see it in action in the 2.0 release 😃
