### ISSUE TITLE
Specify minLines

### ISSUE THREAD

**Issue by Chralu** [Cretezy/flutter_linkify#73]
Hi,

thanks for that great widget :)

`SelectableLinkify` expose `maxLines` property which is pretty handy.
In some cases, you could need for `minLines` as well.

I will submit a simple fix to pass `minLines` to the underlying text widget.

**Comment by Cretezy** [comment]
Fixed with https://github.com/Cretezy/flutter_linkify/pull/74 (release v4.1.0)
