### ISSUE TITLE
Could not launch LinkElement

### ISSUE THREAD

**Issue by didielf** [Cretezy/flutter_linkify#86]
Using exactly the same code from the exampele
Exception has occurred.
"Could not launch LinkElement: 'https://cretezy.com' (cretezy.com)"

seems that canLaunch(link.url) fails. The link will launch without using the canLaunch

**Comment by Cretezy** [comment]
This would be a problem `url_launcher`, not this package.

Please refer to `url_launcher`'s documentation on this
